name = "Kingdoms of the Valley RP"
author = "Oleksandr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e879b4726e1d243682ba0a8eef2d24103c1885d5e24ca70c6ed9d1d3a7c6f908"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
