name = "Kingdoms of the Valley RP"
author = "Oleksandr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e743726fb6513a5273c84c6da249157f38f2802dd73ac55ffa6cf8ad7b145656"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
