name = "Kingdoms of the Valley RP"
author = "Oleksandr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f266e82b67f55bc27c8ad5a95d91b20453e1316cc5e9a0ca2343211afa4df8c6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
